apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: lauxy1/producer:latest
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: ROOT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: email
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: producer
  annotations:
   konghq.com/plugins: five-per-min
spec:
  type: NodePort
  selector:
    app: producer
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 31500
